### ISSUE TITLE
Align spelling of logger.warning()

### ISSUE THREAD

**Issue by iainelder** [pre-commit/pygrep-hooks#100]
The spelling here is missing the closing parenthesis.

https://github.com/pre-commit/pygrep-hooks/blob/2ffc74279f14ebb78a24bcbd546217c8e81b3cb8/.pre-commit-hooks.yaml#L45

It looks a bit jarring when used together with `check for eval()`.

```
check for eval().........................................................Passed
use logger.warning(......................................................Passed
```

**Comment by asottile** [comment]
intentional
