### ISSUE TITLE
[python-no-eval] matches `obj.eval()`

### ISSUE THREAD

**Issue by randolf-scholz** [pre-commit/pygrep-hooks#135]
For example, [`model.eval()`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=eval#torch.nn.Module.eval) gets matched.

https://github.com/pre-commit/pygrep-hooks/blob/3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316/.pre-commit-hooks.yaml#L41

The regex should be changed to something like `(?<!(\w\.))eval\(`

**Comment by asottile** [comment]
search the issue tracker, there are several duplicates

**Comment by GriceTurrble** [comment]
@asottile Can you please specify the exact duplicate that points to a fix? This is all I see in the issue tracker:
![image](https://github.com/pre-commit/pygrep-hooks/assets/9964605/68c82c1f-eecf-4ee5-a7ef-68e83b90657f)

Further: I am also getting a false positive when using [`polars.Expr.arr.eval`](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.arr.eval.html), which is not related to `builtins.eval` in any fashion.

Example usage of `arr.eval` as shown [here](https://stackoverflow.com/a/72875807), is used for calculating set intersection:

```python
df.with_column(
    pl.col("a")
    .arr.concat('b')
    # python-no-eval throws an error here:
    .arr.eval(pl.element().filter(pl.count().over(pl.element()) == 2))
    .alias('filtered')
)
```

**Comment by asottile** [comment]
have you read them?

**Comment by GriceTurrble** [comment]
At most I find a closed PR where you [state](https://github.com/pre-commit/pygrep-hooks/pull/103#issuecomment-1080593450) "bad apis should not be allowed".

I can understand the sentiment, but as it stands, this check is now causing a problem with a specific use case, and unless there's a mechanism provided to exclude that line from the check, I have to disable the hook.
