### ISSUE TITLE
`python-check-blanket-type-ignore` should allow line containing only `# type: ignore`

### ISSUE THREAD

**Issue by randolf-scholz** [pre-commit/pygrep-hooks#158]
`mypy` allows ignoring an entire file by adding a `# type: ignore` comment at the top of the file: https://github.com/python/mypy/issues/964.

**Comment by asottile** [comment]
the entire point of it is to be explicit about what you're ignoring.  blanket ignoring a whole file is not in the spirit of the check

**Comment by randolf-scholz** [comment]
Blanket ignoring a whole file is also not in the *"spirit"* of `mypy`, yet they have the option...

**Comment by asottile** [comment]
idk why you seem to be arguing that "check blanket ignores" should be allowing a blanket ignore
