### ISSUE TITLE
Recommended way of disabling a check per instance?

### ISSUE THREAD

**Issue by danlamanna** [pre-commit/pygrep-hooks#16]
I have a snippet of code causing problems with `python-no-log-warn`, particularly the [distutils log object](https://github.com/python/cpython/blob/4b860fd777e983f5d2a6bd1288e2b53099c6a803/Lib/distutils/log.py#L61) has *only* a `warn` method, and not `warning`. What is the recommended way of ignoring the check for this specific instance?

**Comment by asottile** [comment]
Unfortunately there isn't a way to do line-by-line disables currently -- we could extend the regex to have a specific exclude comment, but that would only work for lines which could have comments added to them

I guess the current suggestion is to `exclude: ...` that entire file via the `pre-commit` configuration

**Comment by danlamanna** [comment]
Ah well, good enough for now. Thanks!

**Comment by asottile** [comment]
cheers! thanks for the issue 🎉
