### ISSUE TITLE
python-no-log-warn catches valid methods

### ISSUE THREAD

**Issue by rcuza** [pre-commit/pygrep-hooks#17]
The standard library package `warning` has a `.warn()` method. This check incorrectly blocks when that method is used. 

The description states this is a "A quick check for the deprecated `.warn()` method of python loggers."

As a user, I would expect this check to only check logger objects for usages of the `.warn` method. What I experience is that `warnings.warn()` is being flagged.

**Comment by asottile** [comment]
yeah it's quick and dirty -- it can't possibly type check things and there are going to be situations where it picks up stuff that isn't correct

it's going to have unfixable false positives -- and that's ok

**Comment by asottile** [comment]
though perhaps a negative lookbehind could be done for `warnings\.` -- want to make a PR doing that @rcuza ?

**Comment by rcuza** [comment]
Looks like `'(?<!warnings)\.warn'` would do the trick.

If I can figure out how to run the tests, I'll submit a PR.

**Comment by asottile** [comment]
`pre-commit run --all-files` ;)

**Comment by rcuza** [comment]
I think #18 does the trick.

I just ran `pytest` but I'll try the pre-commit command, too.

**Comment by asottile** [comment]
via #18
