### ISSUE TITLE
NOQA (in capitals) support

### ISSUE THREAD

**Issue by haizaar** [pre-commit/pygrep-hooks#19]
Good day!
Thank you for creating this tool!

Can you please support `# NOQA` as well? It's respected by flake8 linter by goes undetected by this hook.

Thank you,
Zaar

**Comment by asottile** [comment]
I assume you're referring to `python-check-blanket-noqa`?

**Comment by haizaar** [comment]
Yes! Sorry for not mentioning that.

**Comment by asottile** [comment]
available in v1.4.2 -- thanks for the issue! 🎉

**Comment by haizaar** [comment]
Confirming it works! Thanks for such a quick fix.
