### ISSUE TITLE
`python-no-log-warn` name missing closing parenthesis

### ISSUE THREAD

**Issue by JacobBush** [pre-commit/pygrep-hooks#190]
Precommit message looks like this:
```
use logger.warning(......................................................Passed
```

We can see in the [source](https://github.com/pre-commit/pygrep-hooks/blob/d0975351eaa3660d13bc3c045aeb3990733bbdb4/.pre-commit-hooks.yaml#L45) that the name is missing a closing parenthesis:
```yaml
    name: use logger.warning(
```

I presume that the name should be `use logger.warning()`

**Comment by asottile** [comment]
nah the name is correct.  with paren-paren an unobservant user may may think to remove all the parameters

**Comment by JacobBush** [comment]
@asottile I have to disagree
There is [python-no-eval](https://github.com/pre-commit/pygrep-hooks/blob/main/.pre-commit-hooks.yaml#L39) which is named `check for eval()`.

Should it be named `check for eval(` instead?

**Comment by asottile** [comment]
that one is different, it is not making a replacement suggestion
