### ISSUE TITLE
`python-use-type-annotations` wrongfully complains about comments starting with `type`

### ISSUE THREAD

**Issue by apizarro-eb** [pre-commit/pygrep-hooks#22]
For example:
```python
# type is a keyword in python, so don't name a variable that
ticket_type = models.NullCharField(
    max_length=255,
    db_column='type',
)
```
I think we should have the regex check for comments starting with `type:` instead of just `type`.

**Comment by asottile** [comment]
this is intentional, to catch common typos like:

```python
x = 5  # type Optional[int]
```

in your case it's pretty easy to work around, `# `type` is a keyword in ...`, but also I'm not sure that comment is a useful one anyway?

**Comment by hukkinj1** [comment]
I ran into the same issue when creating a byte string by concatenating, doing something like:
```python
raw += b"\x00"  # type for PONG message
```

Maybe catching typos could have its own hook (if necessary), and `python-use-type-annotations` would have a simple spec of complaining about valid comment type annotations? What does @asottile think?

**Comment by asottile** [comment]
I've already put my thoughts above
