### ISSUE TITLE
Don't report specific type ignores

### ISSUE THREAD

**Issue by hmvp** [pre-commit/pygrep-hooks#25]
Since a recent version mypy allows you to silence only specific error codes with `#type: ignore[attr-undefined]`. These get flagged as type comments.. See the first note in https://mypy.readthedocs.io/en/stable/common_issues.html#spurious-errors-and-locally-silencing-the-checker

**Comment by asottile** [comment]
would you like to submit a patch?

**Comment by asottile** [comment]
going to take the silence as a "no" -- #27 implements this

**Comment by asottile** [comment]
this is released as part of v1.5.1 -- thanks again for the issue! 🎉

**Comment by hmvp** [comment]
Thanks for fixing! I didn't have the time to submit a patch myself..
