### ISSUE TITLE
Check for incorrect sphinx directives

### ISSUE THREAD

**Issue by MarcoGorelli** [pre-commit/pygrep-hooks#32]
Hi,

In [pandas](https://github.com/pandas-dev/pandas/blob/master/.pre-commit-config.yaml), there's a local hook which checks for instances of, e.g.
```
    .. warning:
```
instead of
```
   .. warning::
```

:
```yaml
    -   id: incorrect-sphinx-directives
        name: Check for incorrect Sphinx directives
        language: pygrep
        entry: |
            (?x)
            # Check for cases of e.g. .. warning: instead of .. warning::
            \.\.\ (
                autosummary|contents|currentmodule|deprecated|
                function|image|important|include|ipython|literalinclude|
                math|module|note|raw|seealso|toctree|versionadded|
                versionchanged|warning
            ):[^:]
        files: \.(py|pyx|rst)$
```

It's not specific to pandas, and others might find it useful - would a PR to include it in pygrep hooks be welcome?

**Comment by asottile** [comment]
does it make sense to have a list of things instead of:

```
^\s*[a-z]+:$
```

basically, is there ever a case where `.. foo:` is expected / wanted?

**Comment by MarcoGorelli** [comment]
> basically, is there ever a case where .. foo: is expected / wanted?

**Comment by asottile** [comment]
I checked a few repos: pytest-dev/pytest, pandas-dev/pandas, python/cpython and got zero hits, let's go with the simpler regex

as for naming maybe `rst-directives`? `rst-directive-colons`?
