### ISSUE TITLE
rst-backticks: Smarter checks to ignore simple backticks inside rst code blocks

### ISSUE THREAD

**Issue by DiddiLeija** [pre-commit/pygrep-hooks#95]
See https://github.com/pypa/pip/pull/10914, especially https://github.com/pypa/pip/pull/10914#issuecomment-1046557599.

We have Markdown stuff inside an RST code block, and there're Markdown backticks in there. However, the `rst-backticks` hook thinks those backticks are part of the doc (not the code block), so it fails. Can this check be smarter to avoid checking code blocks?

**Comment by asottile** [comment]
I don't believe it can be -- I'd probably either avoid doing that or avoid using the tool and search for something more powerful
